services:
  mysql:
    image: mysql:8.0
    container_name: chat_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  clamav:
    image: clamav/clamav:latest
    container_name: chat_clamav
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav

volumes:
  mysql_data:
  clamav_data:
